WITH DEPARTMENT_WISE_SALARY AS (  -- Joins to get relevant columns from all three tables, and AGG on SALARY based on each Department
    SELECT C.ID AS DEPARTMENT_ID,
    AVG(B.SALARY) AS DEPARTMENT_AVG_SALARY
    FROM EMPLOYEES A
    JOIN SALARY B 
    ON A.ID = B.EMPLOYEEID
    JOIN DEPARTMENT C
    ON A.DEPARTMENT_ID = C.ID
    GROUP BY C.ID
)
SELECT  
C.NAME AS DEPARTMENT, A.NAME AS EMPLOYEE_NAME,
B.SALARY
FROM EMPLOYEES A
JOIN SALARY B 
ON A.ID = B.EMPLOYEEID
JOIN DEPARTMENT C
ON A.DEPARTMENT_ID = C.ID
JOIN DEPARTMENT_WISE_SALARY D
ON C.ID = D.DEPARTMENT_ID
WHERE B.SALARY < D.DEPARTMENT_AVG_SALARY;