WITH COLLATED_DATASET AS (  -- Joins to get relevant columns from all three tables
    SELECT A.ID AS EMPLOYEE_ID, A.NAME AS EMPLOYEE_NAME, 
    B.SALARY, 
    C.NAME AS DEPARTMENT
    FROM EMPLOYEES A
    JOIN SALARY B 
    ON A.ID = B.EMPLOYEEID
    JOIN DEPARTMENT C
    ON A.DEPARTMENT_ID = C.ID
),
RANKED_SALARIES AS (  -- Asign Rank to get the top 3 Salaries for each Department (can have more than 3 Salaries since DENSE_RANK is used)
    SELECT *, 
    DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RN1
    FROM COLLATED_DATASET
)
SELECT DEPARTMENT, EMPLOYEE_NAME, SALARY
FROM RANKED_SALARIES 
WHERE RN1 <= 3;