SELECT DISTINCT 
SUM(CASE WHEN (MONTH(SALE_DATE)=1) OR (MONTH(SALE_DATE)=2) THEN SALES ELSE 0 END) OVER() AS JAN_FEB_SALES,  -- Filter for both month 1 (Jan) and month 2 (Feb)
SUM(CASE WHEN (MONTH(SALE_DATE)=1) THEN SALES ELSE 0 END) OVER() AS JAN_SALES,  -- Filter for month 1 (Jan)
SUM(CASE WHEN (MONTH(SALE_DATE)=2) OR (MONTH(SALE_DATE)=2) THEN SALES ELSE 0 END) OVER() AS FEB_SALES,  -- Filter for month 2 (Feb)
FROM SALES;